1차 기능 구현
dlxortmd987/racing-car pull request #1
Opened 2024-03-11 14:03 UTC by dlxortmd987

더 늦어지면 안될  것 같아 일단 PR 올립니다...

코드 더러운거랑 commit 분리 못한거 죄송해요...

2차 리팩토링 할 때는 테스트 코드 좀 더 보강하겠습니다...!

2024-03-17 13:00 UTC, younghoondoodoom requested changes
고생하셨습니다 ㅎㅎ
제 생각 간단하게 남겼으니 참고 부탁드립니다! 그리고 얼마든지 의견 남겨주세요~!

2024-03-17 13:00 UTC, younghoondoodoom commented on src/main/kotlin/Main.kt
> +    printWinners(result)
실행 포인트 역할을 해주는 함수에서 어플리케이션의 흐름 제어가 되는거 같네요! 분리해보는건 어떨까요?

2024-03-17 13:00 UTC, younghoondoodoom commented on src/main/kotlin/domain/Application.kt
> +    private val carManager = CarManager.from(names)
`Application` 객체에서 `CarManager` 객체를 생성해주네요! 그럼 `CarManager`는 `Application`, `RaceRunner` 모두에 의존 되는데, 이때 발생하는 문제는 없을까요?

2024-03-17 13:00 UTC, younghoondoodoom commented on src/main/kotlin/domain/Application.kt
> +    private val decisionValueGenerator: DecisionValueGenerator = RandomDecisionValueGenerator()
이 부분도 아래 `CarManager`와 같은 의견입니다.

2024-03-17 13:00 UTC, younghoondoodoom commented on src/main/kotlin/domain/CarManager.kt
`CarManager`의 역할이 굉장히 많은거 같아요! 현재 이 객체는 `Car` 데이터들을 관리하고, 경주도 실행하고, 결과 판단도 해주고 있는거 같아요. 현재는 요구사항이 간단하지만, 복잡한 요구사항이 추가될때 이 객체가 빈번하게 바뀔 것 같습니다!

2024-03-17 13:00 UTC, younghoondoodoom commented on src/main/kotlin/domain/RaceRunner.kt
> +            processHistoryManager.appendLineBreak()
도메인 객체에 `presentation`과 관련된 부분이 들어가있는거 같습니다

2024-03-17 13:00 UTC, younghoondoodoom commented on src/main/kotlin/domain/RaceRunner.kt
해당 객체는 현재 `carManager`로 데이터를 전달하고, 횟수만 관리하는 역할인거 같습니다. 해당 객체는 어떤 용도로 생성하신지 궁금합니다!

2024-03-17 13:00 UTC, younghoondoodoom commented on src/main/kotlin/domain/Car.kt
> +    constructor(name: String) : this(name, 0)
`Car(private val name: String, private var position: Int = 0) `
이런식으로 입력하지 않았을때 디폴트 값을 생성하는 기능이 코틀린에 있더라고요!

2024-03-29 06:30 UTC, dlxortmd987 commented on src/main/kotlin/Main.kt
> +    printWinners(result)
음 사실 분리하는게 좋을 것 같긴 한데 막연히 어떤 문제점이 있는지 떠올리지 못해 필요성을 못느꼈습니다..
혹시 해당 함수에서 흐름 제어가 되면 어떤 문제점이 생기나용

2024-03-29 06:40 UTC, dlxortmd987 commented on src/main/kotlin/domain/RaceRunner.kt
> +            processHistoryManager.appendLineBreak()
음 이 부분은 분리를 해야한다고 생각은 했는데 당장 방법은 생각이 안나서 놔뒀습니다.
한번 진행할 때마다 출력을 하는 상황이다보니 좀 더 고민을 해볼게요!

2024-03-29 06:44 UTC, dlxortmd987 commented on src/main/kotlin/domain/RaceRunner.kt
얘를 원래 레이스를 실행시키는 주체로 설계를 했는데요. 위에서 말씀하신대로 CarManage 역할이 많으니 승리한 차를 가져오는 부분을 이 객체로 위임시킬까 합니다.

2024-03-29 06:44 UTC, dlxortmd987 commented on src/main/kotlin/domain/Car.kt
> +    constructor(name: String) : this(name, 0)
오 그렇군요.. 아직 코틀린 기본 기능에 익숙치가 않네요.. 감사합니다!

2024-03-29 06:45 UTC, dlxortmd987 commented on src/main/kotlin/domain/Application.kt
> +    private val carManager = CarManager.from(names)
음 정답은 명확히는 모르겠지만 CarManager가 바뀔 시 바꿔야 하는 범위가 늘어나는거 맞나요?? ㅎㅎ... 잘 모르겠네요..

2024-03-31 08:51 UTC, younghoondoodoom commented on src/main/kotlin/Main.kt
> +    printWinners(result)
실행 포인트 역할을 하는 객체는 딱 그 역할만 해야한다고 생각합니다. 지금은 단순하게 객체 생성해서 시작하면 되지만, 만약 여기저기서 설정 파일을 종합해서 반영해야한다고 가정을 해볼게요. 거기에 흐름을 제어하는 코드까지 포함되어있으면 굉장히 복잡한 코드가 될 가능성이 있을 것 같습니다.

그리고 처음 코드를 보는 사람이 흐름 제어에 대한 코드를 보고싶을때, 바로 실행 포인트 객체를 열어서 확인할까요??

2024-03-31 09:00 UTC, younghoondoodoom commented on src/main/kotlin/domain/Application.kt
> +    private val carManager = CarManager.from(names)
네 맞습니다! `Application` 객체의 `process` 메소드를 보면 객체간의 흐름을 조절하는 역할을 하는데 다른 객체들의 의존성을 관리해주는 것을 보면 di container 역할까지 담당하는 것 같습니다. 너무 많은 책임이 부여된다고 생각합니다!

2024-04-27 18:31 UTC, merged